// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netpower.Intern2022.Responsitories;

#nullable disable

namespace Netpower.Intern2022.Responsitories.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220520130052_demo")]
    partial class demo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.DepartmentModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasAlternateKey("Name");

                    b.ToTable("TB_DEPARTMENT");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.PositionModel", b =>
                {
                    b.Property<Guid>("ID_Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_Department")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID_Position");

                    b.HasAlternateKey("Name");

                    b.HasIndex("FK_Department");

                    b.ToTable("TB_POSITION");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.ProfileModel", b =>
                {
                    b.Property<Guid>("FK_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FK_Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FK_User");

                    b.HasIndex("FK_Role");

                    b.ToTable("TB_PROFILE");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.UserModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("FK_profile")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasAlternateKey("Mail");

                    b.HasAlternateKey("UserName");

                    b.ToTable("TB_USER");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.PositionModel", b =>
                {
                    b.HasOne("Netpower.Intern2022.Entities.Model.DepartmentModel", "position_Department")
                        .WithMany("positionModels")
                        .HasForeignKey("FK_Department")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("position_Department");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.ProfileModel", b =>
                {
                    b.HasOne("Netpower.Intern2022.Entities.Model.PositionModel", "prf_Role")
                        .WithMany("profiles")
                        .HasForeignKey("FK_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netpower.Intern2022.Entities.Model.UserModel", "profile_user")
                        .WithOne("user_profile")
                        .HasForeignKey("Netpower.Intern2022.Entities.Model.ProfileModel", "FK_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("prf_Role");

                    b.Navigation("profile_user");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.DepartmentModel", b =>
                {
                    b.Navigation("positionModels");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.PositionModel", b =>
                {
                    b.Navigation("profiles");
                });

            modelBuilder.Entity("Netpower.Intern2022.Entities.Model.UserModel", b =>
                {
                    b.Navigation("user_profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
